
stages:
  - build
  - test

build_js:
  image: emscripten/emsdk
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir build
    - cd build
    - emcmake cmake -DCMAKE_BUILD_TYPE=Release ..
    - make
    - cd ..
    - mkdir emscripten/js/bin/
    - cp -r build/emscripten/cpp/pqrs-emscripten* emscripten/js/bin/
    - cd emscripten/js
    - npm install
    - npm run-script build-prod
    - cp -r dist ../..
  artifacts:
    paths:
      - dist

build_native:
  image: rikorose/gcc-cmake:gcc-10
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make
    - cd ..
    - mkdir -p dist
    - cp build/bin/scan-*/pqrs-* dist
  artifacts:
    paths:
      - dist

test_native_basic:
  image: python:3.9-buster
  dependencies: 
    - build_native
  stage: test
  script:
    - ls dist
    - cd test
    - pip install -r requirements.txt
    - ./test_basic_testcases.py ../dist/pqrs-scan-one


